#端口号
server:
  port: 9090
#服务名和数据源(连接池)
spring:
  application:
    name: userservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ysluntan?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
#如果feign遇到相同的名字就排除掉
  main:
    allow-bean-definition-overriding: true
#注册地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka